from pydantic import BaseModel, Field
from enum import Enum
from typing import Any
import uuid

class RiskTier(str, Enum):
    read_only = "read_only"
    low_risk_write = "low_risk_write"
    high_risk_write = "high_risk_write"
    critical_write = "critical_write"

class PlanStatus(str, Enum):
    draft = "draft"
    pending_approval = "pending_approval"
    approved = "approved"
    rejected = "rejected"
    executed = "executed"
    failed = "failed"

class Plan(BaseModel):
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))  # generated by Track B when the plan is created
    endpoint: str
    method: str
    parameters: dict[str, Any]
    reason: str
    expected_result: str
    risk_tier: RiskTier
    requires_approval: bool
    requested_by: str
    status: PlanStatus = PlanStatus.draft